# Generated by Django 4.2.6 on 2024-05-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhk', models.CharField(max_length=30)),
                ('photo', models.ImageField(default='a.png', upload_to='uploads')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
            ],
        ),
    ]
